### ISSUE TITLE
选择脚本显示无法读取文件？

### ISSUE THREAD

**Issue by David318** [nondanee/Nroxy#1]
入口脚本选择后显示无法读取文件，手机读写权限已经允许了，不知道是什么意思

**Comment by nondanee** [comment]
读写权限有限，要看文件位置
比如 termux 应用内存储 `/data/data/com.termux/files/...`，在命令行中，没有 root，别的应用是没有读权限的
建议把脚本放到外部存储 `/sdcard` 内

**Comment by David318** [comment]
哦~~~~原来如此，谢谢
