### ISSUE TITLE
报错 java.io.IOException: Error running exec()

### ISSUE THREAD

**Issue by nondanee** [nondanee/Nroxy#2]
在设置仅代理网易云后, 成功有了MITM > music.163.com,但是网易云还是无法连接网络.........
并且还多了MITM > crash.163.com  似乎是崩溃上传bug的网址.
drony报错java.io.IOException:No data received from the server
我还尝试了一下大佬您另一个项目 https://github.com/nondanee/Nroxy
但是报错
```
java.io.IOException: Error running exec(). Command: [sh, -c, node /storage/emulated/0/Download/app.js ] Working Directory: /data/data/dev.nondanee.nroxy/files Environment: [PATH=$PATH:/data/data/dev.nondanee.nroxy/files/usr/bin]
```
_Originally posted by @theFreeWall in https://github.com/nondanee/UnblockNeteaseMusic/issues/282#issuecomment-543815171_

**Comment by nondanee** [comment]
@theFreeWall
你是 Android 10 吗？
如果是的话确实不行

二进制文件来自 dorynode，是 32 位的，Android 10 好像必须 64 位
https://play.google.com/store/apps/details?id=io.tempage.dorynode&hl=zh
你可以试试用 dorynode 运行，看看会不会报错

**Comment by theFreeWall** [comment]
安卓版本5.1,网易云版本3.6.1,wifi网络
dorynode+drony成功!(部分歌曲在下载精度条满2次后依然下载失败)

**Comment by theFreeWall** [comment]
感谢大佬的耐心解答

**Comment by nondanee** [comment]
你试试装一个 terminal https://play.google.com/store/apps/details?id=jackpal.androidterm&hl=zh
或者在 dorynode 的 shell 里运行
或者 pc 上 adb shell
```
sh
which sh
sh -c 'echo helloworld'
```
看看 `sh -c` 能不能用
我怀疑可能是没有 sh 这个命令

**Comment by theFreeWall** [comment]
dorynode 的 shell中sh -c 'echo helloworld'
能够成功出现helloworld

**Comment by nondanee** [comment]
已经修了，在虚拟机上测过没问题
去 release 更新新版吧
