### ISSUE TITLE
无法缓冲歌曲

### ISSUE THREAD

**Issue by theFreeWall** [nondanee/Nroxy#3]
WARNING: linker: node: unused DT entry: type 0x6ffffffe arg 0x34d254
WARNING: linker: node: unused DT entry: type 0x6fffffff arg 0x3
__bionic_open_tzdata_path: ANDROID_ROOT not set!
__bionic_open_tzdata_path: ANDROID_ROOT not set!
HTTP Server running @ http://0.0.0.0:8080
__bionic_open_tzdata_path: ANDROID_ROOT not set!
__bionic_open_tzdata_path: ANDROID_ROOT not set!
__bionic_open_tzdata_path: ANDROID_ROOT not set!
MITM > ip.ws.126.net 
MITM > music.163.com 
TUNNEL - 223.252.199.67:443
MITM > music.163.com 
MITM > g1.163.com 
MITM > mr.da.netease.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > g1.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > p3.music.126.net 
MITM > p3.music.126.net 
MITM > loc.map.baidu.com 
MITM > loc.map.baidu.com 
MITM > loc.map.baidu.com 
MITM > loc.map.baidu.com 
MITM > loc.map.baidu.com 
MITM > loc.map.baidu.com 
MITM > music.163.com 
MITM > music.163.com 
MITM > p2.music.126.net 
MITM > p2.music.126.net 
MITM > p2.music.126.net 
MITM > music.163.com 
MITM > p2.music.126.net 
MITM > music.163.com 
MITM > nstool.netease.com 
MITM > only-914670-122-96-41-145.nstool.zhuanzfx.com 
MITM > music.163.com 
MITM > music.163.com 
[33337002] Welcome To New York (Karaoke Version)
http://nc01.sycdn.kuwo.cn/3c1e19bbeea56a938b1178a350fa09e3/5dad81c0/resource/n2/84/24/1755639558.mp3
MITM > music.163.com

**Comment by theFreeWall** [comment]
利用dorynode+drony代理可以成功使用,用这个显示"无法缓冲歌曲,请检查网络"

**Comment by nondanee** [comment]
前面的 warning 不管应该也没关系吧

我自己一直在用没啥问题 =.=

你试试
dorynode + Nroxy (VPN 服务) 和
Nroxy (Node.js 运行时) + drony 
这两种组合会能不能成功

**Comment by theFreeWall** [comment]
dorynode + Nroxy (VPN 服务)        失败
Nroxy (Node.js 运行时) + drony     成功

**Comment by nondanee** [comment]
这就麻烦了，因为 VPN 那部分不是我写的。。。来自 https://github.com/forbe/tun2http

**Comment by theFreeWall** [comment]
没关系的,我用dorynode+drony能够凑合着用已经很满足了
只是提出来看看能不能解决的
