### ISSUE TITLE
What proxy script is works on this app?

### ISSUE THREAD

**Issue by devflow** [nondanee/Nroxy#6]
Hello. I'm working hard on something similar to this. 😸 

I'm trying nodejs-mobile and it's hard like as your commentary.
Anyway, does the proxy scripts you use works well? I am looking for a possible way to HTTP/S MiTM, but it's difficult because tun2http does not resolve the host of https tunnel (certificate miss-match error.. etc).

thanks!

**Comment by nondanee** [comment]
A proxy script like the sample code in node docs should work.
https://nodejs.org/dist/latest-v12.x/docs/api/http.html#http_event_connect

The server script used README demo is on gist now, you can check it.
https://gist.github.com/nondanee/b064d01dfeae20e418b32df1ef85a0ef

> tun2http does not resolve the host of https tunnel

I'm not clear about your problem.
Do you means the tun2http will resolve domain name to ip, so you cannot directly get the domain name in `server.on('connect')` processing ? (like the screenshot in README, all log show ip but not domain)

You can detect the domain (the "host" in your description) in sni by reading the first packet from `on('connect')` socket
Please refer to https://github.com/buschtoens/sni

Hope it can help you

**Comment by devflow** [comment]
Thanks for your kind answer! 

My goal is MITM to app's https traffics with tun2http. but that is impossible without root 👎 .
App which built for android 7.0 or above doesn't using the android key store's User section as default.
so my concept is failed.

anyway. thanks for answer. happy coding 😄

**Comment by nondanee** [comment]
👌
