### ISSUE TITLE
能提供proxy.js 让我测试吗？

### ISSUE THREAD

**Issue by 411370845** [nondanee/Nroxy#8]
我拷贝项目下来了，启动vpn了，所有APP都没网了

**Comment by nondanee** [comment]
嗯？你不运行代理，又不配黑白名单让所有 APP 走代理，那所有 APP 断网不是必然的吗？

可以，不过你想测试啥？帮我验证 proxy.js 的正确性吗？

**Comment by 411370845** [comment]
想测试APP走nodejs代理，然后看看app发了http、https的请求。但我没在Android里用过nodeJS。所以很好奇Nroxy的工作原理，想了解了解，测试一下

**Comment by nondanee** [comment]
走的是 http 代理，和 node 没什么关系，用 node 可以实现 http 代理，别的语言也能做，没什么稀奇的

只是塞了一个能在 Android 上运行的 node 二进制包来运行 node 文件
其实 node 在哪里都能运行，和 Android 也没什么关系

工作原理是用 [forbe/tun2http](https://github.com/forbe/tun2http) 把 VPNService 转换成 http 代理，http 代理会处理 app 发的请求

demo 文件在 https://gist.github.com/nondanee/b064d01dfeae20e418b32df1ef85a0ef

运行时记得排除 Nroxy，即黑名单添加 Nroxy 或白名单中无 Nroxy
因为 node 创建的 socket 无法被保护，也会走 tunhttp 代理，然后死循环

**Comment by NewBugger** [comment]
> 想测试APP走nodejs代理，然后看看app发了http、https的请求。但我没在Android里用过nodeJS。所以很好奇Nroxy的工作原理，想了解了解，测试一下

如果你对代理有所了解就很容易理解。
