### ISSUE TITLE
Need help with AUTH proxy!

### ISSUE THREAD

**Issue by chr0sy** [nondanee/Nroxy#9]
Hi. First of all nice app! :)

Second i would like to ask you, how to proceed when a proxy has authentication (username and password). Can you kindly help me out, please?

Thanks

**Comment by nondanee** [comment]
The VPNservice part is transplant from [forbe/tun2http](https://github.com/forbe/tun2http) which written by C
It don't support AUTH proxy, and I'm unable to do secondary development

You can do transforming in nodejs (coding more easily than in C)
Just add 'Proxy-Authorization' to request headers

tunhttp <=> local NON-AUTH proxy (nodejs) <=> remote AUTH proxy
